name: PHP

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.4'
        tools: composer:v1
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Lint PHP files using PHP-CS-Fixer
      run: vendor/bin/php-cs-fixer fix --verbose --dry-run --diff --using-cache=no
  analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.4'
        tools: composer:v1
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Analyse PHP files using PHPStan
      run: vendor/bin/phpstan analyse --no-progress
